pipeline {
    agent { docker { image 'python:3.10.1-alpine' } }
    stages {
        stage('build') {
            steps {
                sh """
                    pip3 install pipenv --user &&
                    pipenv install --system --deploy &&
                    pytest
                """
            }
        }
    }
}