pipeline {
    agent { docker { image 'python:3.10' } }
    stages {
        stage('build') {
            steps {
                sh """
                    sudo -H pip3 install --upgrade pip &&
                    sudo -H pip3 install pipenv &&
                    pipenv install --system --deploy &&
                    pytest
                """
            }
        }
    }
}